services:
  - type: web
    name: qr_base_attendance
    env: python
    branch: main
    rootDir: qr_base_attendance_afnhs
    region: singapore
    plan: free

    buildCommand: |
      pip install -r requirements.txt

    startCommand: gunicorn scholarscan.wsgi:application

    postDeploy: >
      python manage.py migrate
      python manage.py seed_data

    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: scholarscan.settings

      - key: DEBUG
        value: "False"

      - key: SECRET_KEY
        generateValue: true
